name: journey
networks:
  proxy:
    external: true

services:
  client:
    image: ghcr.io/yopyzzang/journey:latest
    container_name: journey_client
    restart: unless-stopped
    expose:
      - 5173

  nginx:
    build: ./nginx
    container_name: journey_nginx_proxy
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - client
    networks:
      - default
      - proxy